### ISSUE TITLE
how to use SSL / encryption = required for postgres?

### ISSUE THREAD

**Issue by devinschumacher** [l-v-yonsama/db-notebook#1]
how to use SSL / encryption = required for postgres?

**Comment by l-v-yonsama** [comment]
@devinschumacher 
In v0.2.7, I added a parameter to enable SSL.
Please try it after upgrading.

![ssl_setting](https://github.com/l-v-yonsama/db-notebook/assets/32474032/3fcfa0bd-7e12-4c3d-bccb-b0b34535d343)

**Comment by devinschumacher** [comment]
@l-v-yonsama perfect! connection works now, thank you!
