### ISSUE TITLE
Database Selection issue in Notebooks

### ISSUE THREAD

**Issue by devpkr1** [l-v-yonsama/db-notebook#11]
Hi db-notebook team,

Every time when we use db-notebook for sql queries , we have to write database name before table name , This is quiet annoying .
If we are working on a database then there will be an option to select database schema for all cells in the notebook like you provided for specify connection to all cells.

Everytime when writing queries it is annoying to write database name before table name.
![Screenshot 2024-09-30 165047](https://github.com/user-attachments/assets/d39b7de0-f11b-472d-8e70-02b374e2b02a)

**Comment by l-v-yonsama** [comment]
Hi, @devpkr1 .

It's the same request as this (.#2 ).

I understood that many people avoid qualifying database names by using the appropriate connection settings for each database they want to use.

However, after receiving the same request from two different people, I realized that not everyone is able to use the appropriate connection settings for each database they use.

So I will modify it so that we can run `USE <DATABASE>` behind the scenes before executing SQL if necessary.

https://dev.mysql.com/doc/refman/8.0/en/use.html

**Comment by l-v-yonsama** [comment]
Hi, @devpkr1 .

I've changed to be able to pre-execute `use database statement` on each cells in Ver 0.7.5.

Specify “stock_market” for the “USE DB name” property in the connection settings.

Please try it after upgrading.

<img width="860" alt="スクリーンショット 2024-10-01 9 33 51" src="https://github.com/user-attachments/assets/af931b49-f286-45ff-bba5-d6838cfcaed3">

**Comment by devpkr1** [comment]
Hi I-v-yonsama,

I appreciate your effort  for this update but to make more handy user
friendly approach please create a button in the header of the notebook to
change database schema (that apply to all cells of the notebook)  like u
have given for "specify connection to all"
[image: Screenshot 2024-10-01 090718.png]
Also make the output result header like this.
[image: Screenshot 2024-10-01 110910.png]

Currently it is like this
[image: Screenshot 2024-10-01 110814.png]


Thanks and Regards,
Pradeep Kumar

**Comment by l-v-yonsama** [comment]
Hi, @devpkr1 .
Thank you for your suggestions for improvement.
I cannot see the screenshot. I would like to have it uploaded again.
Thank you very much.

**Comment by devpkr1** [comment]
I appreciate your effort  for this update but to make more handy user
friendly approach please create a button in the header of the notebook to
change database schema (that apply to all cells of the notebook)  like u
have given for "specify connection to all"
[image: Screenshot 2024-10-01 090718.png]
Also make the output result header like this.
[image: Screenshot 2024-10-01 110910.png]

Currently it is like this
[image: Screenshot 2024-10-01 110814.png]

Again if you can't see the screenshot , you can mail me directly -
***@***.***

Thanks & regards
Pradeep Kumar

**Comment by l-v-yonsama** [comment]
Hi, @devpkr1 .

I've changed the way use Database is set up as shown in the attached screenshot.

Please try it after upgrading.

<img width="1063" alt="スクリーンショット 2024-10-02 8 07 35" src="https://github.com/user-attachments/assets/6cf69fb7-542d-4a82-943b-81817c3120fc">

**Comment by devpkr1** [comment]
Hi,

I appreciate your effort in designing the button in the header of the
notebook. However, I have encountered an issue where the button is not
working for all cells in the notebook.

*Specific Issues:*


   - The button is not functional for all cells in the notebook.
   - The "Specify Connection to all" button is also not working for all
   cells in the notebook.


I have attached a screenshot for your reference.

*Request for Enhancement*

Additionally, I would like to request a modification to the "Specify USE-DB
all" button. Instead of typing the database name, could you please make it
a dropdown selection?

Thanks and regards,
Pradeep Kumar

**Comment by l-v-yonsama** [comment]
Hi, @devpkr1 .
Thanks for the test.

The glitch you pointed out is a specification.

The “USE DATABASE” statement only works with MySQL or SQL Server due to the verndor and npm modules used.

Therefore, the command Specify USE-DB all,
The “Specify USE-DB all” command can only be set if the target cell has been determined to be the DB mentioned above. Otherwise, it will be ignored.

The input for the Specify USE-DB all command is a pulldown, which can be set with the
It is not possible due to the vscode API. (This is because the API for a pulldown that can also be used for input is not publicly available.)

Finally, the image is not visible every time.
Please, please, please open Github in your browser to review your post after you submit it.

**Comment by devpkr1** [comment]
Hi,

I appreciate your effort in designing the button in the header of the
notebook. However, I have encountered an issue where the button is not
working for all cells in the notebook.

*Specific Issues:*


   - The button is not functional for all cells in the notebook.
   - The "Specify Connection to all" button is also not working for all
   cells in the notebook.


I have attached a screenshot for your reference.
![Screenshot 2024-10-02 130552](https://github.com/user-attachments/assets/3348f79b-cdfd-452c-b734-b2f83aff5e94)

*Request for Enhancement*

Additionally, I would like to request a modification to the "Specify USE-DB
all" button. Instead of typing the database name, could you please make it
a dropdown selection?

Thanks and regards,
Pradeep Kumar

**Comment by l-v-yonsama** [comment]
Hi, @devpkr1 .

Thanks for attaching the screenshot.
I tried it here and it is still working fine.

![a](https://github.com/user-attachments/assets/cbcd409d-3658-4f14-a745-eeda2635879e)

**Comment by devpkr1** [comment]
Hi ,

As you shown in the screen recording buttons are working but i think you interpreted my issue in wrong way.
Don't create cells before , just create one cell and use "Specify connection to all" and "Specify Use DB all" buttons.
Every time when create new cells you have to set connection and db  . this is the issue and it is annoying , it is not setting by default for all cells.

Thanks and Regards,
Pradeep Kumar

**Comment by l-v-yonsama** [comment]
Hi, @devpkr1 .

I understand the process you want to see implemented, but I think it will only lead to different behavior than expected for everyone but you.
I can't implement it.

**Comment by l-v-yonsama** [comment]
The purpose of this issue is to eliminate database specification from SQL statements.
This issue has been achieved, so it is closed.
