### ISSUE TITLE
Data Output

### ISSUE THREAD

**Issue by Gavin-OP** [l-v-yonsama/db-notebook#15]
When output the data, sometimes I only need the data but do not need the menu or the scripts how I retrieve the data. Could you help to add a selection when export the data to excel, such as detailed export or only data export?

Thank you.

**Comment by l-v-yonsama** [comment]
Hi @Gavin-OP .

Please turn off the checkboxes for the following two parameters in the settings screen of the extension.
- output.Excel: display TOC
- output.Excel: display table-name, sql-statement

Please try it after extension upgrading ver0.7.24.

<img width="1132" alt="スクリーンショット 2024-12-07 11 43 43" src="https://github.com/user-attachments/assets/a49b3399-28ce-4e5d-80ff-f8e1428f780c">
