### ISSUE TITLE
Please add USE keyword. Why is the USE keyword not working?

### ISSUE THREAD

**Issue by lundeen-bryan** [l-v-yonsama/db-notebook#2]
I noticed that I could not use the USE keyword to indicate which database I wanted to use. It meant that I have to write the fully qualified FROM statement including the schema as well as the database name in my SELECT > FROM statements. 

Can you test to see if you can add the USE keyword so I can say USE northwind, or USE sakila for example? Then I won't have to fully qualify the from statement like this:

SELECT categoryid FROM northwind.categories

Instead I want to write:
USE northwind
SELECT categoryid FROM categories

**Comment by l-v-yonsama** [comment]
I'm sorry, but I cannot accommodate this request.

First, the SQL parser used does not support the USE clause.

Even if I replace it with a parser that supports the USE clause, you still have the following problem.
- Only one SQL statement can be written per cell.
- Each SQL cell uses a different connection, specifying a USE clause in the previous cell has no effect on the next cell.
