### ISSUE TITLE
FEATURE REQUEST: keyboard shortcut to specify connection

### ISSUE THREAD

**Issue by lundeen-bryan** [l-v-yonsama/db-notebook#3]
I tried to setup a keyboard shortcut to specify connection but it doesn't work. Can you take a look and see if you can add this feature as a native part of the extension?

**Comment by l-v-yonsama** [comment]
In v0.3.0, I added "keyboard shortcut to specify connection".
See here https://github.com/l-v-yonsama/db-notebook?tab=readme-ov-file#keyboard-shortcuts.

Please try it after upgrading.

**Comment by lundeen-bryan** [comment]
Thank you so much! It works!

**Comment by l-v-yonsama** [comment]
I am glad you like it.
