### ISSUE TITLE
[FEATURE REQUEST] Add SQLite support

### ISSUE THREAD

**Issue by lundeen-bryan** [l-v-yonsama/db-notebook#6]
I have one project that is in SQLite that I'm working on. I tried to convert it to PostgreSQL but it was a little too advanced for me. So I was wondering if it would be very hard to add SQLite support to DB Notebook? 

Use cases would be for developers who only need to do exploratory analysis using SQLite, small projects, and when using SQLite as the db for a web app. 

Typically, the source file is a .db or .sqlite file extension.

**Comment by l-v-yonsama** [comment]
I may try to program SQLite support next month when I have more time!

**Comment by lundeen-bryan** [comment]
Thank you so much. Have a good weekend!

**Comment by lundeen-bryan** [comment]
I was hoping that the SQLite support would be soon. I'm not in a big hurry and I don't know what special features SQLite has other than it usually works from a local file rather than a server. But let me know when to try it. Thank you so much!

**Comment by l-v-yonsama** [comment]
It's almost done.
Now testing.
I will release it tomorrow.

<img width="1095" alt="スクリーンショット 2024-08-01 12 55 00" src="https://github.com/user-attachments/assets/2d68e1c4-87a5-4d4c-b4b8-cf5a64021e0b">

**Comment by l-v-yonsama** [comment]
@lundeen-bryan 
I've changed to be able to use SQLite in Ver 0.5.8.

Please try it after upgrading.

**Comment by lundeen-bryan** [comment]
Works like a charm! thank you so much.
