### ISSUE TITLE
Can we run a UDF in .dbn files? See example

### ISSUE THREAD

**Issue by lundeen-bryan** [l-v-yonsama/db-notebook#7]
SQL Engine is MySQL for the following UDF.

Whe;n trying to create a UDF using a custom delimiter or the standard delimiter, I get an error message:

USING CUSTOM DELIMITER:

```sql
 DELIMITER $$
CREATE FUNCTION addition(
    a FLOAT, b FLOAT
) RETURNS DECIMAL(9,2)
DETERMINISTIC
BEGIN
    DECLARE c DECIMAL(9,2);
    SET c = a + b;
    RETURN c;
END $$
DELIMITER ;
```

The error message is:
```
Execute query Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $$
CREATE FUNCTION addition(
    a FLOAT, b FLOAT
) RETURNS DECIMAL(9,' at line 1
```
Then I tried to create with a standard delimiter:

```sql
CREATE FUNCTION addition(
    a FLOAT, b FLOAT
) RETURNS DECIMAL(9,2)
DETERMINISTIC
BEGIN
    DECLARE c DECIMAL(9,2);
    SET c = a + b;
    RETURN c;
END;
```

I received the following error message:
```
Execute query Error: This command is not supported in the prepared statement protocol yet
```

It may be that the dbn interface might not be compatible with creating UDFs, but I wanted to ask about it and see if you had any ideas about whether it is possible. Otherwise, I just try to run it in a regular *.sql file. 

Thank you so much for your help!

**Comment by l-v-yonsama** [comment]
"This command is not supported in the prepared statement protocol yet", so I will check to see if there is another way to handle this.

**Comment by l-v-yonsama** [comment]
@lundeen-bryan 
I've changed to be able to use create UDF with a standard delimiter in Ver 0.5.3.

Please try it after upgrading.

<img width="641" alt="スクリーンショット 2024-07-15 12 27 32" src="https://github.com/user-attachments/assets/14d32efd-9083-4140-affd-27704c58f4cd">

**Comment by lundeen-bryan** [comment]
Thank you so much! You need to start a buy me a coffee account. This extension is really gold!

It successfully runs the simple UDF with a standard delimiter. 

I even tried a fairly complex UDF that uses a while loop, runs, and provides the correct answer. 

```sql
CREATE FUNCTION factorial(n INT) RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE result INT DEFAULT 1;
    WHILE n > 1 DO
        SET result = result * n;
        SET n = n - 1;
    END WHILE;
    RETURN result;
END;
```

Test query:
```
SELECT factorial(5) AS factorial_result;  -- Should return 120
```

**Comment by l-v-yonsama** [comment]
@lundeen-bryan 
I'm glad it worked out well for you.
Oh, by the way, “by me coffee” is linked at the bottom of README.md. 
If you donate, I'll drink coffee at Starbucks.

https://github.com/l-v-yonsama/db-notebook?tab=readme-ov-file#-donate
or
https://buymeacoffee.com/lvyoshiokai

**Comment by lundeen-bryan** [comment]
Will do. You've done a great job with this extension!

**Comment by l-v-yonsama** [comment]
@lundeen-bryan 
I had a caramel macchiato.
That was a wonderful coffee. Thank you so much.

![DSC_1189](https://github.com/user-attachments/assets/ac34add1-72ec-4e50-91be-20a242614b33)

**Comment by lundeen-bryan** [comment]
Awesome! I like those too.
