### ISSUE TITLE
[BUG REPORT] Can't use a user defined variable see example

### ISSUE THREAD

**Issue by lundeen-bryan** [l-v-yonsama/db-notebook#8]
Hello, 

It doesn't look like I can use user defined variables in the cells. 

```MySQL
SET @ind_rate = 83.52;
SELECT CarName, FORMAT(Price * @ind_rate, 2) "Rupees" FROM cars
```

The error message says:
```
Execute query Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT CarName, FORMAT(Price * @ind_rate, 2) "Rupees" FROM cars' at line 2
```

Perhaps maybe change the error handling so that it gives the user a warning that they cannot use variables? Or if there was a way to use variables that would be really great!

**Comment by lundeen-bryan** [comment]
I realized that you designed it to hold variables in JSON format. 

So it works fine to do it like this:

```json
{
	"ind_rate": 83.52
}
```

Then the variable is called using a colon instead of a @ symbol.

```sql
SELECT CarName, FORMAT(Price * :ind_rate, 2) "Rupees" FROM cars
```

I guess this is not really a bug, but I think maybe the error message can help people know what to do differently. Thank you for the gif that shows how to use variables.

**Comment by l-v-yonsama** [comment]
“If you want to use a variable, please use the bind parameter” message with a link explaining how to use it.
<img width="987" alt="スクリーンショット 2024-07-20 14 51 07" src="https://github.com/user-attachments/assets/987783d3-2487-4d7d-912f-f771e9fcf6cb">

**Comment by lundeen-bryan** [comment]
Glad you added a msg to the user so it helps us know what alternatives to use.
